### ISSUE TITLE
ATOM configuration

### ISSUE THREAD

**Issue by emotiony** [emotiony/xiongc.github.io#1]
### ATOM Plugin List (from A to Z)

+ [advanced-open-file](https://atom.io/packages/advanced-open-file)
+ [atom-beautify](https://atom.io/packages/atom-beautify)
+ [atom-clock](https://atom.io/packages/atom-clock)
+ [atom-ternjs](https://atom.io/packages/atom-ternjs)
+ [editorconfig](https://atom.io/packages/editorconfig)
+ [emmet](https://atom.io/packages/emmet)
+ [expand-region](https://atom.io/packages/expand-region)
+ [expand-selection-to-quotes](https://atom.io/packages/expand-selection-to-quotes)
+ [file-icons](https://atom.io/packages/file-icons)
+ [hey-pane](https://atom.io/packages/hey-pane)
+ [keybinding-cheatsheet](https://atom.io/packages/keybinding-cheatsheet)
+ [linter](https://atom.io/packages/linter)
+ [linter-csslint](https://atom.io/packages/linter-csslint)
+ [linter-eslint](https://atom.io/packages/linter-eslint)
+ [linter-sass-lint](https://atom.io/packages/linter-sass-lint)
+ [pigments](https://atom.io/packages/pigments)
+ [platformio-ide-terminal](https://atom.io/packages/platformio-ide-terminal)

### Theme
+ [atom-material-ui](https://atom.io/themes/atom-material-ui) **UI**
+ [atom-material-syntax](https://atom.io/themes/atom-material-syntax) **schema**

### Style Sheet for the style
``` less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */


/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor::shadow .cursor {
  // border-color: red;
}
atom-text-editor .cursor {
  border-width: 1px;
}

.paint-cursor atom-text-editor .cursor,
.paint-cursor atom-text-editor.editor .cursor {
  border-color: #e3b705;
}

.editor:not(.mini) .cursor {
    height: 16px !important;
    margin-top: 4px;
}

// scrollbar
.scrollbars-visible-always {
  .tree-view-scroller {
      &::-webkit-scrollbar {
          display: none;
          width: 0.25rem;
          height: 0.25rem;
      }
      &:hover::-webkit-scrollbar {
          display: block;
      }
  }
}

::-webkit-scrollbar {
  width: 0.25rem !important;
  height: 0.25rem !important;
}
```
